### ISSUE TITLE
Reusable Description

### ISSUE THREAD

**Issue by kenyoshizoe** [kenyoshizoe/andante#5]
xacroでyamlを読み込んでdescriptionをいい感じにしたい

```yaml
- name: "base"
   height: 0.0
- name: "ld06"
   height: 0.0
- name: "camera_elp"
   height: 0.06
```

みたいな感じ?
